### ISSUE TITLE
isFlexBasis function breaking on IE

### ISSUE THREAD

**Issue by broomroden89** [StevenYuysy/vue-content-placeholder#2] opened 2017-05-11 12:24 UTC
Whilst testing in IE the browser seems to flag up a syntax error regarding the isFlexBasis function, which is in fact breaking the rest of the sites JS making it impossible to use this package until this is fixed. This particular syntax error doesn't appear to be an issue in other browsers I have tested in though. 
![image](https://cloud.githubusercontent.com/assets/18102894/25948780/0dfbbde0-364d-11e7-8cf3-ac8845a00dc3.png)

**Comment by StevenYuysy** [comment] 2017-05-11 16:06
Currently I am using OSX, I will try to find a IE browser to reproduce the issue.

**Comment by StevenYuysy** [comment] 2017-05-14 08:29
I checked it out on IE browser and discover that there is nothing wrong with the isFlexBasis function, since the data had been delivered correctly to the Vue component.

Probably because IE browser partly support flexbox.

**Comment by StevenYuysy** [comment] 2017-05-14 16:04
Fixed in 187b1775be2e097872427b9957aee768f124662d
Work well under IE 11.
![6343319a567a824ad11d71cd8bd9ffc5](https://cloud.githubusercontent.com/assets/11738111/26035621/db6f8a98-3901-11e7-8ee2-6804470140fa.jpg)

**Closed by StevenYuysy** 2017-05-14 16:04 UTC
